<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductStyleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productStyles = [
            "Ale Blonde",
            "Ale brune",
            "Ale de blé Allemande",
            "Ale rousse",
            "Ale Rousse Allemande",
            "Ale Rousse Irlandaise",
            "Ale de style Belge",
            "Ale Sure",
            "Altbier",
            "Blonde Brettée",
            "Barleywine",
            "Belge Forte",
            "Berliner Weisse",
            "Berliner Weisse aux fruits",
            "Bière affinée en barrique",
            "Bière Brettée",
            "Bière de Blé",
            "Bière de riz",
            "Bière sauvage",
            "Bière sure aux fruits",
            "Bitter Anglaise",
            "Blanche",
            "Blanche aux fruits",
            "Blonde d'Abbaye",
            "Bock",
            "Bock Allemand",
            "Brut IPA",
            "California Common",
            "Cold IPA",
            "DDH IPA",
            "Doppelbock",
            "Double IPA",
            "Double NEIPA",
            "Double Belge",
            "Dubbel",
            "Dunkel",
            "Dunkelweizen",
            "Gose",
            "Gose aux fruits",
            "Gose Impériale",
            "Helles",
            "Hopfenweisse",
            "IPA",
            "IPA Americaine",
            "IPA Anglaise",
            "IPA Rousse",
            "NEIPA",
            "NEIPA DDH",
            "NEIPA TDH",
            "West Coast IPA",
            "East Coast IPA",
            "IPA Vermontoise",
            "IPA aux fruits",
            "IPA Belge",
            "IPA Blanche",
            "IPA Noire",
            "IPA DDh",
            "Triple IPA",
            "IPA Brettée",
            "IPA Kveik",
            "IPA TDH",
            "Session IPA",
            "Nano IPA",
            "IPA Sure",
            "IPA Locale",
            "IPA 100% Québecois",
            "India Pale Lager",
            "IPA de style Belge",
            "Kellerbier",
            "Kölsch",
            "Kriek",
            "Kveik Pale Ale",
            "Lager",
            "Lager Ambrée",
            "Lager Brune",
            "Lager mexicaine",
            "Bitter",
            "Lager Viennoise",
            "Lagerbier",
            "Lambic",
            "Marzen",
            "Milkshake IPA",
            "Nano NEIPA",
            "Oud Bruin",
            "Rouge des Flandres",
            "Pale Ale",
            "Pale Ale Américaine",
            "Pale Ale Belge",
            "Pale Ale Houblonnée",
            "Pastry Stout",
            "Pilsner",
            "Pilsner Bohémienne",
            "Pilsner de style Tchèque",
            "Pilsner de style Svetly Lezak",
            "Polotmavy Lezak",
            "Porter",
            "Porter Baltique",
            "Porter Baltique Imperiale",
            "Porter Robuste",
            "Porter Barriquée",
            "Quadruple IPA",
            "Radler",
            "Rauchbier",
            "Roggenbier",
            "Saison",
            "Saison Belge",
            "Saison de Ferme",
            "Sans Alcool",
            "Sans Alcool IPA",
            "Sans Alcool Blonde",
            "Sans Alcool Blanche",
            "Sans Alcool Sure aux fruit",
            "Sans Alcool Berliner Weiss",
            "Sans alcool Rousse",
            "Gin sans Alcool",
            "Schwarzbier",
            "Scotch Ale",
            "Session IPA",
            "Session IPL",
            "Session Lager",
            "Stout",
            "Stout Impérial",
            "Svetly Vycepni",
            "Triple Belge",
            "Scotch Ale Wee Heavy",
            "Weissbier",
            "Weizenbock",
            "Kveik Pale Ale",
            "Other"
        ];

        foreach ($productStyles as $style) {
            DB::table('product_styles')->insert([
                'name' => $style,
                'created_at' => now(),
                'updated_at' => now()
            ]);
        }
    }
}
